blank_issues_enabled: false
contact_links:
    - name: Vencord Support Server
      url: https://discord.gg/5Xh2W87egW
      about: "Need Help? Join our support server and ask in the #support channel!"
